version: '3.2'

services:
  db:
    image: postgres:15
    container_name: motogp_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motogp_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}

volumes:
  postgres_data:
