version: '3.2'

services:
  db:
    image: postgres:15
    container_name: motogp_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - settings.env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motogp_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./settings.env


volumes:
  postgres_data:
